uint8 AccPed
uint8 AccPed_enable
uint8 ADM_FaultLevel
uint8 Fog_Light
uint8 Horn
uint8 Hydraulic_Brake
uint8 High_BeamLigh
uint8 Low_BeamLight
uint8 Turn_Signal
uint8 Double_Light

uint8 Night_Light
uint8 Defroster_Control
uint8 Wiper_Control
uint8 Amble_Brake
uint8 Compartment_Control
uint8 finish_over
uint8 Emergency_Brake
uint8 Load_Brake
uint8 Engine_Start
uint8 Engine_Stop
uint8 Road_DryorWet
uint8 Switch_DynamicorEconomical
uint8 Slope
uint8 Gear
float32 GPS1_Curvature_cmd

